#!Groovy
pipeline {
    agent {
       node {
            label 'Ansible'
        }
        
    }
    options {
        buildDiscarder(logRotator(numToKeepStr: '5'))
    }
    environment {
        DOCKERHUB_CREDENTIALS = credentials('dockerhub')
    }
    stages{
            stage ('1.Install Docker') {
          steps{
          sh'ansible-playbook Ansible/install_docker.yml'
          }
        }
            stage('2.Start Ansible playbook') {
    steps {
        sh 'ansible-playbook Ansible/SS_EDUP.yml'
      }
    }
    
    
  }

