pipeline{

	agent {
        node {
            label 'Ansible'
        }  
    }
	
	stages {
       
        stage ('1.Push to DockerHub') {
          steps{
          withCredentials([string(credentialsId: 'Docker_push', variable: 'qwerty-1')]) {
  sh 'ansible-playbook Ansible/Docker-push.yml --ask-vault-pass --extra-vars "<(echo \$VAULT_PASSWORD)"'
        }
    

  }
		}
}
}
