#!Groovy
pipeline {
    agent {
       node {
            label 'Ansible'
        }
    }
    stages {
        stage ('1. Show current path'){   
          steps{
              sh 'pwd'
        }
            }
        stage ('2.Install Docker') {
          steps{
           ansiblePlaybook credentialsId: 'ansible', disableHostKeyChecking: true, installation: 'Ansible', playbook: 'Ansible/install_docker'
          }
        }


  }
}
