---
- name: Install Docker and Docker Compose on EC2 instances
  hosts: AWS_SERVERS
  vars:
    docker_username: "alkaponees"
    docker_password: "ALk4pone007"
  become: yes
  gather_facts: yes
  tasks:
    - name: Login to DockerHub
      docker_login:
        username: "{{ docker_username }}"
        password: "{{ docker_password }}"
    - name: Push Docker image to DockerHub
      shell: docker push alkaponees/ss_edup:latest