---
- name: Run Terraform
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Initialize Terraform
      command: terraform init
      args:
        chdir: ${HOME}/Command_Diploma/Terraform
    - name: Apply Terraform plan
      command: terraform apply -auto-approve
      args:
        chdir: ${HOME}/Command_Diploma/Terraform
