---
- name: Run Terraform
  hosts: localhost
  vars:
    public_ip_address: "{{ public_ip_address }}"
  gather_facts: false
  tasks:
    - name: Initialize Terraform
      command: terraform init
      args:
        chdir: ${HOME}/Command_Diploma/Terraform(Workstation)
    - name: Apply Terraform plan
      command: terraform apply -auto-approve
      args:
        chdir: ${HOME}/Command_Diploma/Terraform(Workstation)
    - name: Display public IP address
      debug:
        var: public_ip_address
