#!Groovy
pipeline {
    agent {
       node {
            label 'Ansible'
        }
    }
    stages {
        stage ('1. Show current path'){   
          steps{
              sh 'pwd'
        }
            }
        stage ('2.Destroy Workstation on AWS') {
          steps{
          sh'''
            #!/bin/sh
            ansible-playbook Ansible/terraform_workstation_destroy.yml"
            '''
          }
        }
    

  }
}
